### ISSUE TITLE
Morning Short?

### ISSUE THREAD

**Issue by sitver** [guipdutra/awesome-geek-podcasts#111]
Would you consider adding my podcast, [Morning Short](http://listen.morningshort.com), to your list?

**Comment by guipdutra** [comment]
Hey, @sitver!
We usually just add podcasts related to tech/geek stuff.
It seems this is not Morning Short's subject. Am I right?

If you know a podcast that fit in our proposal and is not in the list yet, ou can add it by yourself. See more about how to contribute [here](https://github.com/guipdutra/awesome-geek-podcasts/blob/master/CONTRIBUTING.md).
