### ISSUE TITLE
add the Myths and Legends podcast

### ISSUE THREAD

**Issue by NonlinearFruit** [guipdutra/awesome-geek-podcasts#128]
[This](https://www.mythpodcast.com/about/) is a podcast dedicated to telling legendary stories as closely to the originals as possible. It is a little offbeat from the _tech_ side, but esoteric knowledge the of the ancient and medieval stories that played a large role in shaping pop and modern culture, sounds _geeky_ to me. But I also understand that this list of podcasts revolves more around the _techie_ side.

---
- [Myths and Legends](https://www.mythpodcast.com/about/) - Dedicated to telling legendary stories as closely to the originals as possible.

---

**[Note:** I am not affiliated with Myths and Legends, just a fan **]**

**Comment by ayr-ton** [comment]
@NonlinearFruit Do you want to provide a PR adding this podcast?

**Comment by ayr-ton** [comment]
I will leave this one closed for now. And when we got new commits/comments/PRs we could reopen o/
