### ISSUE TITLE
Updated/Outdated flags

### ISSUE THREAD

**Issue by LedZeck** [guipdutra/awesome-geek-podcasts#158]
Could be interesting add at README.md the current status of each podcast?

Something like:

- Generic Podcast <Updated in YYYY-MM-DD>
- Random Podcast <Updated in YYYY-MM-DD>

**Comment by ayr-ton** [comment]
Do you want to help providing a PR, @LedZeck?

**Comment by LedZeck** [comment]
I almost don't remember that i have opened this issue.

But, sure... I'll try soon as possible :smiley:

**Comment by ayr-ton** [comment]
I will leave this one closed for now. And when we got new commits we could reopen o/
