### ISSUE TITLE
Merge between other list awesome-podcast.

### ISSUE THREAD

**Issue by enieber** [guipdutra/awesome-geek-podcasts#172]
Exist another list by podcast with more style and may is very nice if make the merge between https://github.com/ogilvieira/awesome-podcasts-br with this awesome-geek-podcast.

**Comment by ayr-ton** [comment]
@guipdutra Could I work on that?

**Comment by ayr-ton** [comment]
@enieber Quick question. By merge, do you mean only the podcasts list, right? Or do you refer to the code functionalities as well?

**Comment by enieber** [comment]
may be nice to do the merge by functionalities, because in the project by @ogilvieira has mush functionalities very nice in the site.

**Comment by ayr-ton** [comment]
@enieber Could you provide a PR of this?

**Comment by ayr-ton** [comment]
@enieber Do you still want to merge both?

**Comment by ayr-ton** [comment]
I will leave this close for now and when we got a response we could reopen this one.
