### ISSUE TITLE
Commentary

### ISSUE THREAD

**Issue by sindresorhus** [guipdutra/awesome-geek-podcasts#22]
> A curated list of podcasts **we like to listen to.**

Why? - Is my first question when looking at the items. I can Google "geek podcasts" and get a similar lists. I want to know why I should bother listen to them. Would be useful if you would add commentary and require new podcast entries to come with it.
## 

It's been very useful to have commentary in [awesome-scifi](https://github.com/sindresorhus/awesome-scifi#cities-in-flight-by-james-blish-40).

**Comment by ayr-ton** [comment]
@sindresorhus Do you mind adding some samples so we could see if it is suitable? As we have a big list I don't know if is too much work adding commentaries to all links.

**Comment by sindresorhus** [comment]
Look at https://github.com/sindresorhus/awesome-scifi#cities-in-flight-by-james-blish-40, it has many samples. You don't have to do all of them. Just add commentary to some as a start.

**Comment by ayr-ton** [comment]
I will leave this one closed for now. And when we got new commits/comments/PRs we could reopen o/
