### ISSUE TITLE
Group podcasts by topic.

### ISSUE THREAD

**Issue by yoihito** [guipdutra/awesome-geek-podcasts#55]
Hey! I think it would be cool to group podcasts by topic. For example Ruby, Javascript or similar.

**Comment by cv** [comment]
Good idea - would it make sense to split up the `README.md` file at this point?

**Comment by zachlysobey** [comment]
This is a bit tricky I would think as I think it would be difficult to separate everything into clear and distinct categories. We could perhaps brainstorm some ideas?

**Exploring the JavaScript "topic"**:
- There are NodeJS specific podcasts
- We have framework-specific podcasts (Angular, React...)
- There are general JS podcasts
- There are podcasts that frequently discuss JS, but are not specific to JS

Podcasts like ShopTalk I would be tempted to put in a category like "Front-end web development", as well as "the Web Ahead" or "Web Platform", yet these do go into different technologies now and again. And would JS be under "Front-end web development" (or just _some_ js, and other content under Node)

There are also some items listed like ThoughtBot and DevChat.tv which actually contain multiple podcasts. These, of course, would have to be split out as well.

Perhaps I can suggest that we create, **in addition to** the main README.md, separate curated lists for different topics?

**Comment by cv** [comment]
> Perhaps I can suggest that we create, in addition to the main README.md, separate curated lists for different topics?

I like that idea a lot more – maybe we could test a `JAVASCRIPT.md` with some of the suggestions you mentioned?

**Comment by adamveld12** [comment]
I would like to contribute the AWS re:Invent podcasts but they don't seem to fit the format and all of the podcasts on this list seem to be ongoing series and not one off things like talks.

These podcasts are very substantial (the 2015 re:Invent one has 230+ individual talks in it alone) and there are some really great ones. This type of stuff would find a better home and be much more welcomed if there was a talks section.

**Comment by ayr-ton** [comment]
Does someone still want to provide a PR with a suggestion for this?

**Comment by ayr-ton** [comment]
I will leave this one closed for now. And when we got new commits/comments/PRs we could reopen o/
