### ISSUE TITLE
OPML Feed

### ISSUE THREAD

**Issue by RobLoach** [guipdutra/awesome-geek-podcasts#73]
Have an OPML feed of them all so that it's easy to subscribe to them all at once.

**Comment by jars** [comment]
@RobLoach,

I have selected ~90% of the podcasts and OPML'd them in my [newsbeuter](https://github.com/jordanarseno/newsbeuter/blob/master/opml.xml) repository.

A tip: If you're running Android, download [SGit](https://play.google.com/store/apps/details?id=me.sheimi.sgit&hl=en) and [AntennaPod](https://play.google.com/store/apps/details?id=de.danoeh.antennapod&hl=en) from the Play Store. You can clone the repository onto your phone with SGit and import the opml.xml file into AntennaPod.

Works a treat. Cheers

**Comment by RobLoach** [comment]
Very cool! Well done :+1: ... I'll try this one out!

**Comment by zachlysobey** [comment]
This is very cool.

I think it would be pretty awesome to actually merge this into this repo -- and bring that number to 100% for each language. @jordanarseno what do you think?

**Comment by jars** [comment]
@RobLoach and @zachlysobey -- i'll write up a topic customization script, re-package the repo as "geek podcasts opml" or something, and ping you guys to add your custom casts as pull reqs. thx for the interest & stay tuned.

**Comment by jars** [comment]
Incomplete, but something like [this](https://github.com/jordanarseno/engine-ears) @RobLoach @zachlysobey -- you can customize the tags you want with `tags init` and build the opml from your tags using `opml make` (see readme). The URLs are stored in the root `.yaml` file.

**Comment by zachlysobey** [comment]
That is awesome -- a great name too!

Very close to exactly what I have been thinking about doing except you actually implemented it!

**Comment by ayr-ton** [comment]
Does someone still want to merge this into this repo? @jordanarseno?

**Comment by ayr-ton** [comment]
I will leave this one closed for now. And when we got new commits/comments/PRs we could reopen o/
